<template>
<div>
    <el-tabs type="border-card">
        <el-tab-pane label="基础指标">
            <span style="font-weight:bold;">基础信息</span> 
                    <table border="1px" width= "100%">
                        <tr>
                            <td>板块/领域</td>
                            <td colspan="3" align="center" valign="middle">核电板块</td>
                            <td  colspan="3" align="center" valign="middle">新能源板块</td>
                            <td  colspan="3" align="center" valign="middle">核燃料板块</td>
                            <td  colspan="3" align="center" valign="middle">金融板块</td>
                            <td>核服集团</td>
                            <td>核技术公司</td>
                            <td>节能公司</td>
                            <td>能源国际</td>
                            <td>总计</td>
                        </tr>
                        <tr>
                            <td>单位/项目名称</td>
                            <td>运营公司</td>
                            <td>工程公司</td>
                            <td>研究院</td>
                            <td>苏州院</td>
                            <td>大亚湾公司</td>
                            <td>阳江公司</td>
                            <td>宁德公司</td>
                            <td>红岩河公司</td>
                            <td>防城港公司</td>
                            <td>台山公司</td>
                            <td>陆丰公司</td>
                            <td>惠州公司</td>
                            <td>苍南公司</td>
                            <td>广利核公司</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>自有员工总人数（人）</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>安质环监督人员数量（人）</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                         <tr>
                            <td>承包商/供应商人数（人）</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                         <tr>
                            <td>当月员工工时数（万人工时）</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                         <tr>
                            <td>当月承包商工时数（万人工时）</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </table>
        </el-tab-pane>
        <el-tab-pane label="结果指标">
             <span style="font-weight:bold;"> 安质环绩效情况</span> 
                    <table border="1px" width= "100%">
                        <tr>
                            <td>板块/领域</td>
                            <td colspan="3" align="center" valign="middle">核电板块</td>
                            <td  colspan="3" align="center" valign="middle">新能源板块</td>
                            <td  colspan="3" align="center" valign="middle">核燃料板块</td>
                            <td  colspan="3" align="center" valign="middle">金融板块</td>
                            <td>核服集团</td>
                            <td>核技术公司</td>
                            <td>节能公司</td>
                            <td>能源国际</td>
                            <td>总计</td>
                        </tr>
                        <tr>
                            <td>单位/项目名称</td>
                            <td>运营公司</td>
                            <td>工程公司</td>
                            <td>研究院</td>
                            <td>苏州院</td>
                            <td>大亚湾公司</td>
                            <td>阳江公司</td>
                            <td>宁德公司</td>
                            <td>红岩河公司</td>
                            <td>防城港公司</td>
                            <td>台山公司</td>
                            <td>陆丰公司</td>
                            <td>惠州公司</td>
                            <td>苍南公司</td>
                            <td>广利核公司</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>死亡事故(人次)</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>重伤事故（人次）</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                         <tr>
                            <td>轻伤事故（人次）</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                         <tr>
                            <td>限工事故(人次)</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                         <tr>
                            <td>医学处置事件(人次)</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                         <tr>
                            <td>急救箱事件(人次)</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                         <tr>
                            <td>重大未遂(起)</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                         <tr>
                            <td>一般未遂(起)</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                         <tr>
                            <td>其他财产损失事故（起）无人员伤害但直接财产损失超100万</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                         <tr>
                            <td>因安质环事项被政府通报或处罚（次）</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </table>
        </el-tab-pane>
        <el-tab-pane label="过程指标">
             <span style="font-weight:bold;">安质环过程控制情况</span> 
                    <table border="1px" width= "100%">
                        <tr>
                            <td>板块/领域</td>
                            <td colspan="3" align="center" valign="middle">核电板块</td>
                            <td  colspan="3" align="center" valign="middle">新能源板块</td>
                            <td  colspan="3" align="center" valign="middle">核燃料板块</td>
                            <td  colspan="3" align="center" valign="middle">金融板块</td>
                            <td>核服集团</td>
                            <td>核技术公司</td>
                            <td>节能公司</td>
                            <td>能源国际</td>
                            <td>总计</td>
                        </tr>
                        <tr>
                            <td>区域巡检覆盖率（%）</td>
                            <td>运营公司</td>
                            <td>工程公司</td>
                            <td>研究院</td>
                            <td>苏州院</td>
                            <td>大亚湾公司</td>
                            <td>阳江公司</td>
                            <td>宁德公司</td>
                            <td>红岩河公司</td>
                            <td>防城港公司</td>
                            <td>台山公司</td>
                            <td>陆丰公司</td>
                            <td>惠州公司</td>
                            <td>苍南公司</td>
                            <td>广利核公司</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>安质环专题会议（次）</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>安全培训（人次）</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                         <tr>
                            <td>安全投入（万元）</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                         <tr>
                            <td>应急演练（次）</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                         <tr>
                            <td>应急值班抽查在岗率（%)</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                         <tr>
                            <td>开展安质环经验反馈的次数（次）</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>经验反馈纠正行动完成率（%）</td>
                             <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </table>
        </el-tab-pane>
    </el-tabs>
</div>
</template>

<script>
export default {
    data() {
        return {
        }
    },
    methods:{
    }
}
</script>
